### ISSUE TITLE
AdminFlag column inside the `user` table.

### ISSUE THREAD

**Issue by ErikApoyy** [mslfh/xt_server#28]
**Current behaviour:**
The 'AdminFlag' column is set to be int with NULL value as default. 

**Issue:**
All registered account can access the AdminJS page with their normal account.

**Expected behaviour:**
1. Only account with admin privilege can access the AdminJS page as it consists of confidential information. 
2. All new registered account (Except the 'admin@example.com' upon running the server for first time) must have no admin privilege.

**Possible solution:**
1. Modify the .sql file and change the 'AdminFlag' as boolean.
2. In the AdminJS login page, implement new logic that check their 'AdminFlag' status. Deny entry for account with **_false_** 'AdminFlag' value.

**Comment by abluejay-piyo** [comment]
We have  layers of admin access: super admin, org manager, department manager, user.

I want to finalise PWA login page first. Then, we can port the page to admin.

@KMtouzhele is working on porting UI. I am waiting for one piece from Fuhai before making your work online.
